DoAnWeb/DoAnWeb_2/DoAnWeb_2/Areas/Admin/Controllers/LoaiSanPhamAdminController.cs
using DoAnWeb_2.Areas.Admin.Models.BusAdmin;
using DoAnWeb2ShopConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnWeb_2.Areas.Admin.Controllers
{
    public class LoaiSanPhamAdminController : Controller
    {
        [Authorize(Roles = "Admin")]
        // GET: Admin/LoaiSanPhamAdmin
        public ActionResult Index()
        {
            if (TempData["Success"] != null)
            {
                ViewBag.Success = TempData["Success"].ToString();
            }
            if (TempData["Error"] != null)
            {
                ViewBag.Error = TempData["Error"].ToString();
            }
            var sql = LoaiSanPhamBusAdmin.DanhSachSanPham();
            return View(sql);
        }

        // GET: Admin/LoaiSanPhamAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/LoaiSanPhamAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiSanPhamAdmin/Create
        [HttpPost]
        public ActionResult Create(LoaiSanPham sp)
        {
            try
            {
                // TODO: Add insert logic here

                sp.TinhTrang = 1;

                LoaiSanPhamBusAdmin.Them(sp);
                TempData["Success"] = "Thêm thành công !";
            }
            catch
            {
                TempData["Success"] = "Thêm không công !";
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/LoaiSanPhamAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            var sql = LoaiSanPhamBusAdmin.Update(id);
            return View(sql);
        }

        // POST: Admin/LoaiSanPhamAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, LoaiSanPham sp)
        {
            try
            {
                // TODO: Add update logic here

                sp.TinhTrang = 1;
                LoaiSanPhamBusAdmin.UpdateDS(sp);
                TempData["Success"] = "Chỉnh sữa thành công !";
            }
            catch
            {
                TempData["Success"] = "Chỉnh sữa không công !";
            }
            return RedirectToAction("Index");
        }

    

        // POST: Admin/LoaiSanPhamAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {

            // TODO: Add delete logic here
            try
            {
                // TODO: Add delete logic here
                LoaiSanPhamBusAdmin.XoaTam(id);
                TempData["Success"] = "Xoa thanh cong !";
            }
            catch
            {
                TempData["Error"] = "Xoa khong thanh cong !";
            }

            return RedirectToAction("Index");
        }
    }
}

DoAnWeb/DoAnWeb_2/DoAnWeb_2/Areas/Admin/Views/LoaiSanPhamAdmin/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<style>
    input[type=submit] {
        width: 62.8%;
        padding: 12px 20px;
        margin: 3px 0 0 7cm;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

        input[type=submit]:hover {
            background-color: #bf2222;
        }
</style>

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        @ViewBag.Error
    </div>
}
else if (ViewBag.Success != null)
{
    <div class="alert alert-success" role="alert">
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <span class="sr-only">Success:</span>
        @ViewBag.Success
    </div>
}
<div class="container">
    @using (Html.BeginForm("Create", "LoaiSanPhamAdmin", FormMethod.Post))
    {
        <div class="row" style="margin-top:40px;">
            <div class="form-group col-sm-10">
                <div class="form-group col-sm-3" style="text-align: center;">
                    <label>Mã Sãn Phẩm:</label>
                </div>
                <div class="form-group col-sm-7">
                    <input type="text" size="100" name="MaLoaiSanPham" value="Mã nhà sản xuất" disabled />
                </div>
            </div>
            <div class="form-group col-sm-10">
                <div class="form-group col-sm-3" style="text-align: center;">
                    <label>Tên Sản Phẩm:</label>
                </div>
                <div class="form-group col-sm-7">
                    <input type="text" size="100" name="TenLoaiSanPham" placeholder="Tên Sản Phẩm..." required />
                </div>
            </div>
            @*<div class="form-group col-sm-10">
                    <div class="form-group col-sm-3">
                        <label>Tình Trạng:</label>
                    </div>
                    <div class="form-group col-sm-7">
                        <select id="country" name="TinhTrang" style="width:138%;" >
                            <option value="0">Chưa Khóa</option>
                            <option value="1">Đã Khóa</option>
                        </select>
                    </div>
                </div>*@

            <input type="submit" value="Lưu">
        </div>
    }
</div>

DoAnWeb/DoAnWeb_2/DoAnWeb_2/Areas/Admin/Views/LoaiSanPhamAdmin/Edit.cshtml
@model DoAnWeb2ShopConnection.LoaiSanPham
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<style>
    input[type=submit] {
        width: 62.8%;
        padding: 12px 20px;
        margin: 3px 0 0 7cm;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

        input[type=submit]:hover {
            background-color: #bf2222;
        }
</style>
@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        @ViewBag.Error
    </div>
}
else if (ViewBag.Success != null)
{
    <div class="alert alert-success" role="alert">
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <span class="sr-only">Success:</span>
        @ViewBag.Success
    </div>
}
<div class="container">
    @using (Html.BeginForm("Edit", "LoaiSanPhamAdmin", FormMethod.Post))
    {
        <div class="row" style="margin-top:40px;">
            <div class="form-group col-sm-10">
                <div class="form-group col-sm-3" style="text-align: center;">
                    <label>  </label>
                </div>
                <div class="form-group col-sm-7">
                    <input type="hidden" size="100" name="MaLoaiSanPham" value="@Model.MaLoaiSanPham" />
                </div>
            </div>
            <div class="form-group col-sm-10">

                <div class="form-group col-sm-3" style="text-align: center;">
                    <label>Mã Sãn Phẩm:</label>
                </div>
                <div class="form-group col-sm-7">
                    <input type="text" size="100" value="@Model.MaLoaiSanPham" disabled />
                </div>

            </div>
            <div class="form-group col-sm-10">
                <div class="form-group col-sm-3" style="text-align: center;">
                    <label>Tên Sản Phẩm:</label>
                </div>
                <div class="form-group col-sm-7">
                    <input type="text" size="100" name="TenLoaiSanPham" value="@Model.TenLoaiSanPham" required />
                </div>
            </div>
            <input type="submit" value="Lưu">
        </div>
    }
</div>

DoAnWeb/DoAnWeb_2/DoAnWeb_2/Areas/Admin/Views/LoaiSanPhamAdmin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
    <link href="~/Areas/assets/css/myAdmin.css" rel="stylesheet" />
}

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        @ViewBag.Error
    </div>
}
else if (ViewBag.Success != null)
{
    <div class="alert alert-success" role="alert">
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <span class="sr-only">Success:</span>
        @ViewBag.Success
    </div>
}
<table class="nhasanpham">
    <tr class="tc">
        <th>Mã loại sản phẩm</th>
        <th>Tên loại sản phẩm</th>
        <th>Tình Trạng</th>
        <th colspan="2"><a href="@Url.Action("Create","LoaiSanPhamAdmin")"><img src="~/Areas/assets/img/Add.png" /> </a></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.MaLoaiSanPham</td>
            <td>@item.TenLoaiSanPham</td>
            <td >Đã sử dụng</td>

            <td>
                <a href="@Url.Action("Edit", "LoaiSanPhamAdmin",new {id=@item.MaLoaiSanPham })"><img src="~/Areas/assets/img/edit.png" /></a>
            </td>
            <td>
                <form method="post" action="@Url.Action("Delete","LoaiSanPhamAdmin")">
                    <input type="hidden" name="id" value="@item.MaLoaiSanPham" />
                    <button type="submit"><img src="~/Areas/assets/img/delete.png" /></button>
                </form>
            </td>
        </tr>
    }
</table>