DoAnWeb_2/DoAnWeb_2/Areas/Admin/Controllers/ThungRacSanPhamController.cs
using DoAnWeb_2.Areas.Admin.Models.BusAdmin;
using DoAnWeb2ShopConnection;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnWeb_2.Areas.Admin.Controllers
{
    public class ThungRacSanPhamController : Controller
    {
        // GET: Admin/ThungRacSanPham
        [Authorize(Roles = "Admin")]
        public ActionResult Index(int PagedList = 1, int size = 4)
        {

            if (TempData["Success"] != null)
            {
                ViewBag.Success = TempData["Success"].ToString();
            }
            if (TempData["Error"] != null)
            {
                ViewBag.Error = TempData["Error"].ToString();
            }
            var sql = SanPhamBusAdmin.DanhSachSanPhamThungRac().ToPagedList(PagedList, size);
            return View(sql);
        }

        // GET: Admin/ThungRacSanPham/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/ThungRacSanPham/Create
        public ActionResult Create()
        {

            ViewBag.MaLoaiSanPham = new SelectList(SanPhamBusAdmin.LoaiDS(), "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.MaNhaSanXuat = new SelectList(SanPhamBusAdmin.LayNhaSanXuat(), "MaNhaSanXuat", "TenNhaSanXuat");
            return View();
        }

        // POST: Admin/ThungRacSanPham/Create
        [HttpPost, ValidateInput(false)]
        public ActionResult Create(SanPham sp)
        {
            try
            {
                if (HttpContext.Request.Files.Count > 0)
                {
                    var hpf = HttpContext.Request.Files[0];
                    if (hpf.ContentLength > 0)
                    {
                        string fileName = Guid.NewGuid().ToString();
                        string fullPathWithFileName = "/assets/images/" + fileName + ".jpg" + ".png";
                        hpf.SaveAs(Server.MapPath(fullPathWithFileName));
                        sp.HinhAnh = fullPathWithFileName;
                    }
                }
                // TODO: Add insert logic here
                sp.TinhTrang = 0;
                SanPhamBusAdmin.Them(sp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/ThungRacSanPham/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.MaLoaiSanPham = new SelectList(SanPhamBusAdmin.LoaiDS(), "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.MaNhaSanXuat = new SelectList(SanPhamBusAdmin.LayNhaSanXuat(), "MaNhaSanXuat", "TenNhaSanXuat");
            var sql = SanPhamBusAdmin.Updata(id);
            return View(sql);
        }

        // POST: Admin/ThungRacSanPham/Edit/5
        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(SanPham sp)
        {
            try
            {
                if (HttpContext.Request.Files.Count > 0)
                {
                    var hpf = HttpContext.Request.Files[0];
                    if (hpf.ContentLength > 0)
                    {
                        string fileName = Guid.NewGuid().ToString();
                        string fullPathWithFileName = "/assets/images/" + fileName + ".jpg" + ".png";
                        hpf.SaveAs(Server.MapPath(fullPathWithFileName));
                        sp.HinhAnh = fullPathWithFileName;
                    }
                }
                // TODO: Add insert logic here
                sp.TinhTrang = 0;
                SanPhamBusAdmin.UptadaDS(sp);
                TempData["Success"] = "Chỉnh sữa thành công !";
            }
            catch
            {
                TempData["Success"] = "Chỉnh sữa không công !";
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/ThungRacSanPham/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/ThungRacSanPham/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult DeleteDS(int id)
        {
            try
            {
                // TODO: Add delete logic here
                SanPhamBusAdmin.DeleteThungRac(id);
                TempData["Success"] = "Xóa thành công !";
            }
            catch
            {
                TempData["Error"] = "Xóa không thành công  !";
            }

            return RedirectToAction("Index");
        }
    }
}

DoAnWeb_2/DoAnWeb_2/Areas/Admin/Views/ThungRacSanPham/Create.cshtml
@model DoAnWeb2ShopConnection.SanPham
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}


@using (Html.BeginForm("Create", "ThungRacSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control tinymce" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManHinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManHinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManHinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HeDieuHanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HeDieuHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HeDieuHanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CaneraTruoc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CaneraTruoc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CaneraTruoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CameraSau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CameraSau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CameraSau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ram, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ram, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ram, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BoNhoTrong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BoNhoTrong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BoNhoTrong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DungLuongPin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DungLuongPin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DungLuongPin, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imagefile" style="width: 100%;" />
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiSanPham", null, htmlAttributes: new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaLoaiSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNhaSanXuat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNhaSanXuat", null, htmlAttributes: new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNhaSanXuat, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group col-sm-12">
            <div class="form-group col-sm-2">
                <label>Chọn Sản phẩm mới hay nổi bật:</label>
            </div>
            <div class="form-group col-sm-9">
                <select id="country" name="Home" style="width:100%;">
                    <option value="1">Sản phẩm nổi bật</option>
                    <option value="0">Sản phẩm mới</option>
                    <option value="3">Khác</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoAnWeb_2/DoAnWeb_2/Areas/Admin/Views/ThungRacSanPham/Edit.cshtml
@model DoAnWeb2ShopConnection.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "ThungRacSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="hidden" value="@Model.MaSanPham" name="MaSanPham" />
            </div>
        </div>
        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4 " style="padding-left:200px">
                <label>Tên sản phẩm:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Màn Hình:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.ManHinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManHinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Màn Hình:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.HeDieuHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HeDieuHanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Canera Trước:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.CaneraTruoc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CaneraTruoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Canera Sau:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.CameraSau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CameraSau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Giá:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>CPU:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.CPU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Ram:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.Ram, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ram, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Bộ nhớ trong:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.BoNhoTrong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BoNhoTrong, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Dung lượng pin:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.DungLuongPin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DungLuongPin, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Mô tả:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control tinymce" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Hình ảnh:</label>
            </div>
            <div class="form-group col-sm-7">
                <input type="file" value="@Model.HinhAnh" name="imagefile" style="width: 100%;" />
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Mã lại sản phẩm:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.DropDownList("MaLoaiSanPham", null, htmlAttributes: new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaLoaiSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Mã nhà sản xuất:</label>
            </div>
            <div class="form-group col-sm-7">
                @Html.DropDownList("MaNhaSanXuat", null, htmlAttributes: new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNhaSanXuat, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group col-sm-12">
            <div class="form-group col-sm-4" style="padding-left:200px">
                <label>Chọn Sản phẩm mới hay nổi bật:</label>
            </div>
            <div class="form-group col-sm-7">
                <select id="country" value="@Model.Home" name="Home" style="width:70%;">
                    <option value="1">Sản phẩm nổi bật</option>
                    <option value="0">Sản phẩm mới</option>
                    <option value="3">Khác</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoAnWeb_2/DoAnWeb_2/Areas/Admin/Views/ThungRacSanPham/Index.cshtml
@model PagedList.IPagedList<DoAnWeb2ShopConnection.SanPham>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        @ViewBag.Error
    </div>
}
else if (ViewBag.Success != null)
{
    <div class="alert alert-success" role="alert">
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <span class="sr-only">Success:</span>
        @ViewBag.Success
    </div>
}
<style>
    table {
        border: 1px solid black;
        border-collapse: collapse;
        width: 80%;
    }

    th, td {
        border: 1px solid black;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    th {
        background-color: #4CAF50;
        color: white;
    }
</style>
<body>

    <h2>Danh Sách Sản Phẩm</h2>
    <div>
        <table>
            <tr>
                <th>Mã mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Hình ảnh</th>
                <th>Giá</th>
                <th>Màn hình</th>
                <th>Mô tả</th>
                <th>Hệ điều hành</th>
                <th>Camera trước</th>
                <th>Camera sau</th>
                <th>Cpu</th>
                <th>Ram</th>
                <th>Bộ nhớ trong</th>
                <th>Dung lượng pin</th>
                <th>Tình trạng</th>
                <th colspan="2">
                    <a href="@Url.Action("Create","ThungRacSanPham")"> <img src="~/Areas/assets/img/Add.png" /></a>
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.MaSanPham</td>
                    <td>@item.TenSanPham</td>
                    <td>
                        <img src="@item.HinhAnh" style="width:70px;height:90px;" />
                    </td>
                    <td>@item.Gia</td>
                    <td>@item.ManHinh</td>
                    <td>@Html.Raw(item.MoTa)</td>
                    <td>@item.HeDieuHanh</td>
                    <td>@item.CaneraTruoc</td>
                    <td>@item.CameraSau</td>
                    <td>@item.CPU</td>
                    <td>@item.Ram</td>
                    <td>@item.BoNhoTrong</td>
                    <td>@item.DungLuongPin</td>
                    <td>Ngưng Bán</td>
                    <td>
                        <a href="@Url.Action("Edit","ThungRacSanPham",new {id =@item.MaSanPham })" *@> <img src="~/Areas/assets/img/edit.png" /></a>
                    </td>
                    <td>
                        <form method="post" action="@Url.Action("DeleteDS","ThungRacSanPham")">
                            <input type="hidden" name="id" value="@item.MaSanPham" />
                            <button type="submit"><img src="~/Areas/assets/img/khoiphuc.png" /></button>
                        </form>
                    </td>

                </tr>
            }
        </table>
        <div class="row text-center">
            <ul class="pagination">
                @Html.PagedListPager(Model, PagedList => Url.Action("Index", new { PagedList }))
            </ul>
        </div>
    </div>
</body>