DoAnWeb/DoAnWeb_2/DoAnWeb_2/Controllers/HomeController.cs
using DoAnWeb_2.Models.BUS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnWeb_2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var sql = SanPhamBUS.DanhSachTranHome();
            return View(sql);
        }
        public ActionResult Details(int id)
        {
            var sql = SanPhamBUS.ChiTietDS(id);
            return View(sql);
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DoAnWeb/DoAnWeb_2/DoAnWeb_2/Controllers/SanPhamController.cs
using DoAnWeb_2.Models.BUS;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnWeb_2.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        public ActionResult Index(int PagedList = 1, int size = 8)
        {
            var sql = SanPhamBUS.DanhSachSanPham().ToPagedList(PagedList, size);
            return View(sql);
        }

        public ActionResult Details(int id)
        {
            var sql = SanPhamBUS.ChiTietDS(id);
            return View(sql);
        }

    }
}

DoAnWeb/DoAnWeb_2/DoAnWeb_2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DoAnWeb/DoAnWeb_2/DoAnWeb_2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DoAnWeb/DoAnWeb_2/DoAnWeb_2/Views/Home/Index.cshtml
@model IEnumerable<DoAnWeb2ShopConnection.SanPham>
@using DoAnWeb_2.Models.BUS

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Mainlayout.cshtml";
    <link href="~/assets/css/mycss.css" rel="stylesheet" />

}

<div id="page-content" class="home-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- Carousel -->
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators hidden-xs">
                        <li data-target="#carousel-example-generic" data-slide-to="1" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                    </ol>
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div class="item active">
                            <img src="~/assets/images/logo2.png" alt="First slide">
                            <!-- Static Header -->
                            <div class="header-text hidden-xs">
                                <div class="col-md-12 text-center">
                                </div>
                            </div><!-- /header-text -->
                        </div>
                        <div class="item">
                            <img src="~/assets/images/logo3.png" alt="Second slide">
                            <!-- Static Header -->
                            <div class="header-text hidden-xs">
                                <div class="col-md-12 text-center">
                                </div>
                            </div><!-- /header-text -->
                        </div>
                        <div class="item">
                            <img src="~/assets/images/logo4.png" alt="Third slide">
                            <!-- Static Header -->
                            <div class="header-text hidden-xs">
                                <div class="col-md-12 text-center">
                                </div>
                            </div><!-- /header-text -->
                        </div>
                    </div>
                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div><!-- /carousel -->
            </div>
        </div>
        <div class="row">
            <div class="banner">
                <div class="col-sm-4">
                    <img src="~/assets/images/tienich.jpg" />
                </div>
                <div class="col-sm-4">
                    <img src="~/assets/images/ngua.jpg" />
                </div>
                <div class="col-sm-4">
                    <img src="~/assets/images/thietke.jpg" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="heading"><h2>Sản Phẩm Nổi Bật</h2></div>
                <div class="products">
                    @foreach (var item in Model)
                    {
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="product">
                                <div class="image"><a href="@Url.Action("Details","SanPham", new { id = @item.MaSanPham })"><img src=@item.HinhAnh></a></div>
                                <div class="buttons">
                                    <a class="btn cart" href="#"><span class="glyphicon glyphicon-shopping-cart"></span></a>
                                    <a class="btn wishlist" href="#"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a class="btn compare" href="#"><span class="glyphicon glyphicon-transfer"></span></a>
                                </div>
                                <div class="caption">
                                    <div class="name"><a href="@Url.Action("Details","SanPham", new { id = @item.MaSanPham }) "><h3>@item.TenSanPham</h3></a></div>
                                    <div class="price"><p>@string.Format("{0:#,0 Vnđ}", @item.Gia)</p></div>
                                    <div class="rating"><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star-empty"></span></div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="row">
            <div class="banner">
                <div class="col-sm-6">
                    <img src="~/assets/images/aicap.png" />
                </div>
                <div class="col-sm-6">
                    <img src="~/assets/images/amazon.png" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="heading"><h3>Sản Phẩm Mới</h3></div>
                <div class="products">
                    
                    @foreach (var i in SanPhamBUS.DanhSachTranHome1())
                    {

                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="product">
                                <div class="image"><a href="@Url.Action("Details","SanPham", new { id = @i.MaSanPham })"><img src=@i.HinhAnh></a></div>
                                <div class="buttons">
                                    <a class="btn cart" href="#"><span class="glyphicon glyphicon-shopping-cart"></span></a>
                                    <a class="btn wishlist" href="#"><span class="glyphicon glyphicon-heart"></span></a>
                                    <a class="btn compare" href="#"><span class="glyphicon glyphicon-transfer"></span></a>
                                </div>
                                <div class="caption">
                                    <div class="name"><a href="@Url.Action("Details","SanPham", new { id = @i.MaSanPham }) "><h3>@i.TenSanPham</h3></a></div>
                                    <div class="price"><p>@string.Format("{0:#,0 Vnđ}", @i.Gia)</p></div>
                                    <div class="rating"><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star-empty"></span></div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>